### ISSUE TITLE
Can't find single SNP p-values

### ISSUE THREAD

**Issue by raqueldias** [FelixHeinrich/MIDESP#2]
Is there a way to export the single SNP p-values (fdr corrected) as part of the output files generated by MIDESP?
It seems like only the MI scores are returned by SignificanceFinder.findSignificantScores(), despite it seems to calculate the p-values for everything. My lab and collaborators need those p-values to do gene set and pathway enrichment analysis, so it would be wonderful if you could add that feature.

**Comment by FelixHeinrich** [comment]
Hi, I have added the pvalues for the single SNPs to the output. The files `outputfile.sigSNPs` and `outputfile.allSNPs` will contain the pvalues for the respective MI scores.
